### ISSUE TITLE
AttributeError: YAML object has no attribute YAMLError

### ISSUE THREAD

**Issue by dvaccarosenna** [accanto-systems/lmctl#25]
Attribute error thrown when trying to push an invalid Descriptor, e.g:

```
description: descriptor for TestDuplicateKey
composition:
  a:
    type: resource::t_simple::1.0
  a:
    type: resource::t_simple::1.0
```
